// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbDw1BZe1m1Mkt73Xo7e1ZS5nrxge7FpE',
    appId: '1:161030257652:web:6448050911b3daa80557a1',
    messagingSenderId: '161030257652',
    projectId: 'sastastay-1d420',
    authDomain: 'sastastay-1d420.firebaseapp.com',
    storageBucket: 'sastastay-1d420.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5lweTY8XpatalR0knkkSHfXrVtJDJy4c',
    appId: '1:161030257652:android:db91bba5f9b217e60557a1',
    messagingSenderId: '161030257652',
    projectId: 'sastastay-1d420',
    storageBucket: 'sastastay-1d420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGDPBsI1AOA5bxZMOLs1u_rN_wz9UQKU',
    appId: '1:161030257652:ios:c3b20e120d168eaf0557a1',
    messagingSenderId: '161030257652',
    projectId: 'sastastay-1d420',
    storageBucket: 'sastastay-1d420.firebasestorage.app',
    androidClientId: '161030257652-asleoefo2bop372c04dblmhfdampdvtv.apps.googleusercontent.com',
    iosClientId: '161030257652-gbq0hiktop6v0a6870a3ed8nbup8f8ef.apps.googleusercontent.com',
    iosBundleId: 'com.sastastays.user',
  );

}